# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

In [ ]:
import numpy as np

Convertendo o valor passado como argumento(1.0) para o tipo float32 da biblioteca numpy

In [ ]:
x = np.float32(1.0)
x

1.0

Convertendo os valores passados como argumento para o tipo inteiro padrão, que nesse caso é int64, gerando um array com valores do tipo int64

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

Criando um array 'z', cujos elementos são do tipo uint8, pois passamos como argumento 'dtype=np.uint8' para o método arange

O método arange cria um array com valores igualmente espaçados, nesse caso, ele começa em 0 e termina em 2(excluindo o 3), com step igual a 1

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

Criando array a partir de lista, cujos elementos são do tipo float32, pois passamos como argumento '' dtype='f' ''

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

Criando um novo array a partir do array 'z', mas o tipo dos seus elementos é float64

In [ ]:
z.astype(float)

array([0., 1., 2.])

Criando um novo array a partir do array 'z', cujos elementos têm tipo int8, pois realizamos uma conversão usando o método np.int8()

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')